[project]
name = "agentic-ai-full-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dioumadev221", email = "dioumadione004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "certifi>=2026.7.22",
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.6",
    "langchain-tavily>=0.2.18",
    "langchain-tools>=0.1.34",
    "python-dotenv>=1.2.3",
    "readability-lxml>=0.9",
    "requests>=2.34.2",
    "streamlit>=1.64.0",
    "tavily>=1.1.0",
    "trafilatura>=2.2.0",
]

[project.scripts]
agentic-ai-full-course = "agentic_ai_full_course:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
